## PROFILE OPTION
spring:
  profiles:
    active: local
  devtools:
    livereload: ## STATIC RELOAD
      enabled: true
    restart: ## RESTART WAS
      enabled: false
  freemarker:
    cache: false

## SERVER PORT
server:
  port: 8080
  ## HTTP EXCEPTION
  error:
    include-exception: false
    include-stacktrace: never
    path: "/error"
    whitelabel:
      enabled: true

## LOG LEVEL
logging:
  level:
    root: info
    com.example.websocket: debug
